export const caps = {
  version: 2,
  transport: {
    success: "{ok:true,result}",
    failure: "{ok:false,error:{code,message}} on stderr; exit 1",
    pagination: "{items,total,offset,next}; next=null ends pagination",
    errors: [
      "INVALID_ARGUMENT",
      "UNKNOWN_COMMAND",
      "CONFLICT",
      "FORBIDDEN",
      "NOT_FOUND",
      "DELETED",
      "INTERNAL",
    ],
    retry:
      "Reuse operationId and identical parameters and actor on write retries",
  },
  commands: {
    status: {},
    "resources.upsert": {
      url: "HTTP(S) URL",
      title: "string",
      tags: "string[]",
    },
    "resources.list": {
      query: "optional",
      includeArchived: "optional boolean",
      offset: "integer",
      limit: "1..200",
    },
    "resources.update": {
      id: "resource ID",
      expectedRevision: "integer",
      tags: "string[]",
      title: "string",
    },
    "anchors.upsert": {
      resourceId: "ID",
      quote: "text",
      context: "text",
      start: "seconds|null",
      end: "seconds|null",
      prefix: "text",
      suffix: "text",
    },
    "anchors.list": { resourceId: "ID", offset: "integer", limit: "1..200" },
    "records.get": { id: "ID; includes deleted records for inspection" },
    "trash.list": { query: "optional", offset: "integer", limit: "1..200" },
    "records.setDeleted": {
      id: "resource/vocabulary/note/occurrence ID",
      deleted: "boolean; false restores; parent must be restored first",
      expectedRevision: "integer",
      operationId: "unique request ID",
    },
    "records.history": { id: "ID" },
    "notes.append": {
      anchorId: "ID",
      text: "text",
      discussionId: "optional ID",
      operationId: "unique request ID",
    },
    "notes.update": {
      id: "ID",
      text: "text",
      expectedRevision: "integer",
      operationId: "unique request ID",
    },
    "notes.list": {
      resourceId: "optional",
      query: "optional",
      offset: "integer",
      limit: "1..200",
    },
    "vocabulary.save": {
      anchorId: "ID",
      word: "text",
      meaning: "text",
      language: "default en",
      operationId: "unique request ID",
    },
    "vocabulary.update": {
      id: "vocabulary ID; stable across word corrections",
      word: "text; updates all occurrences; rejects existing word in same language",
      expectedRevision: "integer",
      operationId: "unique request ID",
    },
    "occurrences.update": {
      id: "occurrence ID",
      meaning: "text; this context only",
      expectedRevision: "integer",
      operationId: "unique request ID",
    },
    "vocabulary.list": {
      query: "optional",
      due: "boolean",
      offset: "integer",
      limit: "1..200",
    },
    "occurrences.list": {
      resourceId: "optional",
      vocabularyId: "optional",
      offset: "integer",
      limit: "1..200",
    },
    "reviews.record": {
      vocabularyId: "ID",
      rating: "again|hard|good",
      feedbackSource:
        "optional user-confirmed; explicit user feedback relayed by Agent",
      operationId: "unique request ID",
    },
    "reviews.list": {
      vocabularyId: "optional ID",
      offset: "integer",
      limit: "1..200",
    },
    "discussions.create": {
      anchorId: "ID",
      question: "text",
      noteId: "optional note ID; must belong to anchorId",
      selected: "optional text",
      selectionTranslation: "optional text",
      operationId: "unique request ID",
    },
    "context.export": { anchorId: "ID", discussionId: "optional" },
    search: { query: "text", offset: "integer", limit: "1..200" },
    stats: {},
    "activity.list": {
      offset: "integer",
      limit: "1..200",
      description:
        "Human captures and user-confirmed reviews (including Agent relay); use createdAt in viewer timezone",
    },
    "resources.setArchived": {
      id: "resource ID",
      expectedRevision: "integer",
      archived: "boolean; archiving requires empty resource",
    },
    export: {},
    "jobs.submit": {
      type: "transcript|translate|lookup|seek",
      resourceId: "ID",
      anchorIds: "for translate, up to 4 IDs",
      anchorId: "for lookup",
      text: "selected text",
      seconds: "for seek",
    },
    "jobs.get": { id: "ID" },
    "jobs.list": {
      resourceId: "optional ID",
      offset: "integer",
      limit: "1..200",
    },
    "jobs.cancel": { id: "ID" },
    "translations.list": {
      resourceId: "ID",
      offset: "integer",
      limit: "1..200",
    },
    "backup.import": {
      data: "export object; merges identical IDs, rejects conflicts",
      operationId: "unique request ID",
    },
  },
};
