export const caps = {
  version: 1,
  commands: {
    status: {},
    "resources.upsert": {
      url: "HTTP(S) URL",
      title: "string",
      tags: "string[]",
    },
    "resources.list": {
      query: "optional",
      offset: "integer",
      limit: "1..200",
    },
    "resources.update": {
      id: "resource ID",
      expectedRevision: "integer",
      tags: "string[]",
      title: "string",
    },
    "anchors.upsert": {
      resourceId: "ID",
      quote: "text",
      context: "text",
      start: "seconds|null",
      end: "seconds|null",
      prefix: "text",
      suffix: "text",
    },
    "anchors.list": { resourceId: "ID", offset: "integer", limit: "1..200" },
    "records.get": { id: "ID" },
    "records.history": { id: "ID" },
    "notes.append": {
      anchorId: "ID",
      text: "text",
      discussionId: "optional ID",
      operationId: "unique request ID",
    },
    "notes.update": {
      id: "ID",
      text: "text",
      expectedRevision: "integer",
      operationId: "unique request ID",
    },
    "notes.list": {
      resourceId: "optional",
      query: "optional",
      offset: "integer",
      limit: "1..200",
    },
    "vocabulary.save": {
      anchorId: "ID",
      word: "text",
      meaning: "text",
      language: "default en",
      operationId: "unique request ID",
    },
    "vocabulary.list": {
      query: "optional",
      due: "boolean",
      offset: "integer",
      limit: "1..200",
    },
    "occurrences.list": { resourceId: "optional", vocabularyId: "optional" },
    "reviews.record": {
      vocabularyId: "ID",
      rating: "again|hard|good",
      operationId: "unique request ID",
    },
    "reviews.list": {},
    "discussions.create": { anchorId: "ID", question: "text" },
    "context.export": { anchorId: "ID", discussionId: "optional" },
    search: { query: "text", offset: "integer", limit: "1..200" },
    stats: {},
    export: {},
    "jobs.submit": {
      type: "transcript|translate|lookup|seek",
      resourceId: "ID",
      anchorIds: "for translate, up to 4 IDs",
      anchorId: "for lookup",
      text: "selected text",
      seconds: "for seek",
    },
    "jobs.get": { id: "ID" },
    "jobs.list": {},
    "jobs.cancel": { id: "ID" },
    "translations.list": { resourceId: "ID" },
    "backup.import": {
      data: "export object; merges identical IDs, rejects conflicts",
      operationId: "unique request ID",
    },
  },
};
